# Generated by Django 4.1.2 on 2022-10-20 12:54

from django.db import migrations, models
import wagtail
import wagtail.contrib.forms.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_custom_form_builder_pages"),
    ]

    operations = (
        [
            migrations.AddField(
                model_name="testcaptchaemailformfield",
                name="clean_name",
                field=models.CharField(
                    blank=True,
                    default="",
                    help_text="Safe name of the form field, the label converted to ascii_snake_case",
                    max_length=255,
                    verbose_name="name",
                ),
            ),
            migrations.AddField(
                model_name="testcaptchaformfield",
                name="clean_name",
                field=models.CharField(
                    blank=True,
                    default="",
                    help_text="Safe name of the form field, the label converted to ascii_snake_case",
                    max_length=255,
                    verbose_name="name",
                ),
            ),
            migrations.AddField(
                model_name="testcustomformbuildercaptchaemailformfield",
                name="clean_name",
                field=models.CharField(
                    blank=True,
                    default="",
                    help_text="Safe name of the form field, the label converted to ascii_snake_case",
                    max_length=255,
                    verbose_name="name",
                ),
            ),
            migrations.AddField(
                model_name="testcustomformbuildercaptchaformfield",
                name="clean_name",
                field=models.CharField(
                    blank=True,
                    default="",
                    help_text="Safe name of the form field, the label converted to ascii_snake_case",
                    max_length=255,
                    verbose_name="name",
                ),
            ),
            migrations.AlterField(
                model_name="testcaptchaemailformfield",
                name="choices",
                field=models.TextField(
                    blank=True,
                    help_text="Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.",
                    verbose_name="choices",
                ),
            ),
            migrations.AlterField(
                model_name="testcaptchaemailformfield",
                name="default_value",
                field=models.TextField(
                    blank=True,
                    help_text="Default value. Comma or new line separated values supported for checkboxes.",
                    verbose_name="default value",
                ),
            ),
            migrations.AlterField(
                model_name="testcaptchaemailformfield",
                name="field_type",
                field=models.CharField(
                    choices=[
                        ("singleline", "Single line text"),
                        ("multiline", "Multi-line text"),
                        ("email", "Email"),
                        ("number", "Number"),
                        ("url", "URL"),
                        ("checkbox", "Checkbox"),
                        ("checkboxes", "Checkboxes"),
                        ("dropdown", "Drop down"),
                        ("multiselect", "Multiple select"),
                        ("radio", "Radio buttons"),
                        ("date", "Date"),
                        ("datetime", "Date/time"),
                        ("hidden", "Hidden field"),
                    ],
                    max_length=16,
                    verbose_name="field type",
                ),
            ),
            migrations.AlterField(
                model_name="testcaptchaemailformpage",
                name="from_address",
                field=models.EmailField(
                    blank=True, max_length=255, verbose_name="from address"
                ),
            ),
            migrations.AlterField(
                model_name="testcaptchaemailformpage",
                name="to_address",
                field=models.CharField(
                    blank=True,
                    help_text="Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.",
                    max_length=255,
                    validators=[wagtail.contrib.forms.models.validate_to_address],
                    verbose_name="to address",
                ),
            ),
            migrations.AlterField(
                model_name="testcaptchaformfield",
                name="choices",
                field=models.TextField(
                    blank=True,
                    help_text="Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.",
                    verbose_name="choices",
                ),
            ),
            migrations.AlterField(
                model_name="testcaptchaformfield",
                name="default_value",
                field=models.TextField(
                    blank=True,
                    help_text="Default value. Comma or new line separated values supported for checkboxes.",
                    verbose_name="default value",
                ),
            ),
            migrations.AlterField(
                model_name="testcaptchaformfield",
                name="field_type",
                field=models.CharField(
                    choices=[
                        ("singleline", "Single line text"),
                        ("multiline", "Multi-line text"),
                        ("email", "Email"),
                        ("number", "Number"),
                        ("url", "URL"),
                        ("checkbox", "Checkbox"),
                        ("checkboxes", "Checkboxes"),
                        ("dropdown", "Drop down"),
                        ("multiselect", "Multiple select"),
                        ("radio", "Radio buttons"),
                        ("date", "Date"),
                        ("datetime", "Date/time"),
                        ("hidden", "Hidden field"),
                    ],
                    max_length=16,
                    verbose_name="field type",
                ),
            ),
            migrations.AlterField(
                model_name="testcustomformbuildercaptchaemailformfield",
                name="choices",
                field=models.TextField(
                    blank=True,
                    help_text="Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.",
                    verbose_name="choices",
                ),
            ),
            migrations.AlterField(
                model_name="testcustomformbuildercaptchaemailformfield",
                name="default_value",
                field=models.TextField(
                    blank=True,
                    help_text="Default value. Comma or new line separated values supported for checkboxes.",
                    verbose_name="default value",
                ),
            ),
            migrations.AlterField(
                model_name="testcustomformbuildercaptchaemailformfield",
                name="field_type",
                field=models.CharField(
                    choices=[
                        ("singleline", "Single line text"),
                        ("multiline", "Multi-line text"),
                        ("email", "Email"),
                        ("number", "Number"),
                        ("url", "URL"),
                        ("checkbox", "Checkbox"),
                        ("checkboxes", "Checkboxes"),
                        ("dropdown", "Drop down"),
                        ("multiselect", "Multiple select"),
                        ("radio", "Radio buttons"),
                        ("date", "Date"),
                        ("datetime", "Date/time"),
                        ("hidden", "Hidden field"),
                    ],
                    max_length=16,
                    verbose_name="field type",
                ),
            ),
            migrations.AlterField(
                model_name="testcustomformbuildercaptchaemailformpage",
                name="from_address",
                field=models.EmailField(
                    blank=True, max_length=255, verbose_name="from address"
                ),
            ),
            migrations.AlterField(
                model_name="testcustomformbuildercaptchaemailformpage",
                name="to_address",
                field=models.CharField(
                    blank=True,
                    help_text="Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.",
                    max_length=255,
                    validators=[wagtail.contrib.forms.models.validate_to_address],
                    verbose_name="to address",
                ),
            ),
            migrations.AlterField(
                model_name="testcustomformbuildercaptchaformfield",
                name="choices",
                field=models.TextField(
                    blank=True,
                    help_text="Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.",
                    verbose_name="choices",
                ),
            ),
            migrations.AlterField(
                model_name="testcustomformbuildercaptchaformfield",
                name="default_value",
                field=models.TextField(
                    blank=True,
                    help_text="Default value. Comma or new line separated values supported for checkboxes.",
                    verbose_name="default value",
                ),
            ),
            migrations.AlterField(
                model_name="testcustomformbuildercaptchaformfield",
                name="field_type",
                field=models.CharField(
                    choices=[
                        ("singleline", "Single line text"),
                        ("multiline", "Multi-line text"),
                        ("email", "Email"),
                        ("number", "Number"),
                        ("url", "URL"),
                        ("checkbox", "Checkbox"),
                        ("checkboxes", "Checkboxes"),
                        ("dropdown", "Drop down"),
                        ("multiselect", "Multiple select"),
                        ("radio", "Radio buttons"),
                        ("date", "Date"),
                        ("datetime", "Date/time"),
                        ("hidden", "Hidden field"),
                    ],
                    max_length=16,
                    verbose_name="field type",
                ),
            ),
        ]
    )
